### ISSUE TITLE
Migrate to .NET Standard

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Reporting#5]
Addin should support .NET Core and Cake CoreCLR runner

**Comment by sajeetharan** [comment]
i would like to take this up. is there a doc on how to do?

**Comment by pascalberger** [comment]
@sajeetharan  That would be great!

Stuff which needs to be done:

- Fork this repository
- Create a new feature branch
- Converted solution to Visual Studio 2017
- Update `Cake.Issues` NuGet package to 0.2.0-beta.1
- Add .NET Standard 1.6 target (multi-target with .NET 4.6)
- Use Visual Studio 2017 AppVeyor image
- Update build script (`setup.cake`) for .NET Core
- Create a pull request for merging the code into `develop`

You can also check https://github.com/cake-contrib/Cake.Issues/pull/6 for the same changes (except updating of the Cake.Issues NuGet package) being done for the Cake.Issues addin.

**Comment by kostyaHrytsyuk** [comment]
Hi!
I updated Cake.Issues to 0.2.0-beta.1 and added .NET Standart 1.6
https://github.com/cake-contrib/Cake.Issues.Reporting/pull/6
